// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	// 商品ID
	ID string `json:"id"`
	// 商品名
	Name string `json:"name"`
	// 価格
	Price int `json:"price"`
	// 商品画像URL
	ImageURL string `json:"imageUrl"`
}
