// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Item defines model for Item.
type Item struct {
	Id       string `json:"id"`
	ImageUrl string `json:"imageUrl"`
	Name     string `json:"name"`
	Price    int32  `json:"price"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Limit 1度に取得する最大件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}
