/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/items": {
    /** 商品リストを取得する */
    get: operations["listItems"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Item: {
      id: string;
      name: string;
      /** Format: int32 */
      price: number;
      imageUrl: string;
    };
    Error: {
      /** Format: int32 */
      code: number;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** 商品リストを取得する */
  listItems: {
    parameters: {
      query?: {
        /** @description 1度に取得する最大件数 */
        limit?: number;
      };
    };
    responses: {
      /** @description 商品一覧を返す */
      200: {
        content: {
          "application/json": components["schemas"]["Item"];
        };
      };
      /** @description エラー */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
